{application,xla,
             [{config_mtime,1782412293},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,inets,ssl,public_key,
                             crypto]},
              {description,"Precompiled XLA binaries"},
              {modules,['Elixir.Collectable.XLA.Checksumer',
                        'Elixir.Mix.Tasks.Xla.Checksum',
                        'Elixir.Mix.Tasks.Xla.Info','Elixir.XLA',
                        'Elixir.XLA.Checksumer','Elixir.XLA.Utils']},
              {registered,[]},
              {vsn,"0.8.0"}]}.
