{application,torchx,
             [{config_mtime,1782412293},
              {compile_env,[{torchx,[add_backend_on_inspect],error},
                            {torchx,[check_shape_and_type],error}]},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,nx]},
              {description,"LibTorch bindings and backend for Nx"},
              {modules,['Elixir.Torchx','Elixir.Torchx.Backend',
                        'Elixir.Torchx.Macro','Elixir.Torchx.NIF',
                        'Elixir.Torchx.NIF.DLLLoader']},
              {registered,[]},
              {vsn,"0.9.2"}]}.
